android {
    compileOptions {
        coreLibraryDesugaringEnabled true          // ← add this line
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'  // ← add this
}
